apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "search.name" . }}
    helm.sh/chart: {{ include "search.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .env: |-
{{- range $key, $value :=  .Values.env }}
    {{ $key }}={{ $value }}
{{- end }}
