{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls }}
{{- if eq .Values.ingress.tls_source "secret" }}
{{- $files := .Files }}
{{- range .Values.ingress.tls }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ if .secretName }}{{ .secretName }}{{ else }}tls-{{ template "search.fullname" $ }}-ingress{{ end }}
  labels:
    app.kubernetes.io/name: {{ include "search.name" $ }}
    helm.sh/chart: {{ include "search.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  tls.crt: {{ .base64Crt }}
  tls.key: {{ .base64Key }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
