apiVersion: v1
kind: Service
metadata:
  name: {{ include "search.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "search.name" . }}
    helm.sh/chart: {{ include "search.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: search-port
      port: {{ .Values.service.port }}
      targetPort: search-port
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "search.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
